# Generated by Django 4.0.6 on 2023-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epitope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=100)),
                ('mhc_ambiguity', models.CharField(max_length=100)),
                ('old_allele_name', models.CharField(max_length=100)),
                ('mhc_convert', models.CharField(max_length=100)),
            ],
        ),
    ]
