# Generated by Django 4.0.6 on 2023-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epitope',
            name='database_source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='mhc_possible',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='epitope',
            name='mhc_ambiguity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='epitope',
            name='mhc_convert',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='epitope',
            name='old_allele_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='epitope',
            name='sequence',
            field=models.CharField(default='', max_length=100),
        ),
    ]
