# Generated by Django 4.0.6 on 2023-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0002_epitope_database_source_epitope_mhc_possible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epitope',
            name='journal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pmid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='test',
            field=models.CharField(default='', max_length=100),
        ),
    ]
