# Generated by Django 4.0.6 on 2023-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0003_epitope_journal_epitope_pmid_epitope_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epitope',
            old_name='database_source',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='epitope',
            old_name='test',
            new_name='date',
        ),
        migrations.AddField(
            model_name='epitope',
            name='dbsource',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='epitopespecies',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='gene',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdbcorrect',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdbwrong',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='qualitative',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='quantitative',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='sourcemolecule',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='sourceorganism',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='tcellid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
