# Generated by Django 4.0.6 on 2023-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0004_rename_database_source_epitope_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epitope',
            name='Response',
            field=models.CharField(default='', max_length=100),
        ),
    ]
