# Generated by Django 4.0.6 on 2023-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0005_epitope_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='epitope',
            name='Ag_Chain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='MHC_Chain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='VA_Chain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='VA_IMGT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='VB_Chain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='VB_IMGT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='bound',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdb_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdbid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
