# Generated by Django 4.0.6 on 2023-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcell', '0006_epitope_ag_chain_epitope_mhc_chain_epitope_va_chain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epitope',
            old_name='pdbcorrect',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='epitope',
            old_name='pdbwrong',
            new_name='pdb_pmid',
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdbamb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epitope',
            name='pdbclear',
            field=models.CharField(default='', max_length=100),
        ),
    ]
