BA = ['antigen-loaded-target, CTL culture',
 'multimer-sort',
 'cultured-T-cells,beads,tetramer-sort',
 'Tetramer-sort',
 'BrdU',
 '51 chromium',
 'dextramer-sort,cultured-T-cells',
 'tetramer-sort,beads',
 'beads,tetramer-sort',
 'biological activity',
 'dextramer-sort,beads',
 'cultured-T-cells,tetramer-sort',
 'cultured-T-cells',
 'cd8null-tetramer-sort',
 'tetramer sort',
 'tetramer-sort,cultured-T-cells',
 'CTL clone',
 'tetramer-sort',
 'RNA/DNA detection',
 'cytometric bead array',
 'pentamer-sort',
 'intracellular staining',
 'dextramer-sort',
 'peptide-restimulation,tetramer-sort',
 'ELISPOT',
 'cla',
 'in vitro assay',
 'CFSE',
 '3H-thymidine',
 'in vivo assay',
 'MHC-peptide-beads,cultivated-t-cells',
 'streptamer-sort',
 'ELISA']

Binding = ['limited-dilution-cloning,antigen-expressing-targets',
 'antigen-loaded-targets',
 'antigen-loaded-targets, limiting-dilution-cloning',
 'binding assay',
 'multimer/tetramer',
 'tetramer-sort,limiting-dilution-cloning',
 'High throughput multiplexed assay',
 'surface plasmon resonance (SPR)',
 'antigen-loaded-targets,antigen-expressing-targets',
 'cultured-T-cells,antigen-expressing-targets',
 'antigen-loaded-targets,cloning-by-limiting-dilution',
 'antigen-loaded-targets, pentamer-sort',
 'antigen-loaded-targets,cultured-T-cells',
 'limiting-dilution-cloning,tetramer-sort',
 'limiting-diffusion-cloning,antigen-expressing-targets',
 'tetramer-sort,antigen-loaded-targed',
 'antigen-loaded-targets,pentamer-sort',
 'antigen-expressing-targetsantigen-loaded-target,limiting-dilution-cloning',
 'antigen-loaded-targets,dextramer-sort',
 'tetramer-sort,antigen-expressing cells,cultured-T-cells',
 'antigen-loaded-targets, tetramer-sort',
 'limiting-dilution-cloning',
 'antigen-loaded-targets,limiting-dilution-cloning']

Cytokine = ['bioassay',
 'reporter gene assay',
 'radio immuno assay (RIA)',
 'RNA/DNA detection',
 'cytometric bead array',
 'ELISPOT',
 'ICS',
 'antigen-loaded-targets, IFNg capture assay',
 'antigen loaded targets, IFNg capture assay',
 'ELISA']

ThreeD = ['x-ray crystallography']

Reference_Table = {
      '3D':ThreeD,
      'Binding Activity':BA,
      'Cytokine release':Cytokine,
      'Binding':Binding
}